import { Subject, Chapter } from './types';

export const SUBJECTS_JEE = [Subject.PHYSICS, Subject.CHEMISTRY, Subject.MATHS];
export const SUBJECTS_NEET = [Subject.PHYSICS, Subject.CHEMISTRY, Subject.BIOLOGY];

export const MOCK_CHAPTERS: Record<Subject, Chapter[]> = {
  [Subject.PHYSICS]: [
    { id: 'p1', name: 'Units and Measurements', subject: Subject.PHYSICS },
    { id: 'p2', name: 'Motion in a Straight Line', subject: Subject.PHYSICS },
    { id: 'p3', name: 'Motion in a Plane', subject: Subject.PHYSICS },
    { id: 'p4', name: 'Laws of Motion', subject: Subject.PHYSICS },
    { id: 'p5', name: 'Work, Energy and Power', subject: Subject.PHYSICS },
    { id: 'p6', name: 'System of Particles and Rotational Motion', subject: Subject.PHYSICS },
    { id: 'p7', name: 'Gravitation', subject: Subject.PHYSICS },
    { id: 'p8', name: 'Mechanical Properties of Solids', subject: Subject.PHYSICS },
    { id: 'p9', name: 'Mechanical Properties of Fluids', subject: Subject.PHYSICS },
    { id: 'p10', name: 'Thermal Properties of Matter', subject: Subject.PHYSICS },
    { id: 'p11', name: 'Thermodynamics', subject: Subject.PHYSICS },
    { id: 'p12', name: 'Kinetic Theory', subject: Subject.PHYSICS },
    { id: 'p13', name: 'Oscillations', subject: Subject.PHYSICS },
    { id: 'p14', name: 'Waves', subject: Subject.PHYSICS },
    { id: 'p15', name: 'Electric Charges and Fields', subject: Subject.PHYSICS },
    { id: 'p16', name: 'Electrostatic Potential and Capacitance', subject: Subject.PHYSICS },
    { id: 'p17', name: 'Current Electricity', subject: Subject.PHYSICS },
    { id: 'p18', name: 'Moving Charges and Magnetism', subject: Subject.PHYSICS },
    { id: 'p19', name: 'Magnetism and Matter', subject: Subject.PHYSICS },
    { id: 'p20', name: 'Electromagnetic Induction', subject: Subject.PHYSICS },
    { id: 'p21', name: 'Alternating Current', subject: Subject.PHYSICS },
    { id: 'p22', name: 'Electromagnetic Waves', subject: Subject.PHYSICS },
    { id: 'p23', name: 'Ray Optics and Optical Instruments', subject: Subject.PHYSICS },
    { id: 'p24', name: 'Wave Optics', subject: Subject.PHYSICS },
    { id: 'p25', name: 'Dual Nature of Radiation and Matter', subject: Subject.PHYSICS },
    { id: 'p26', name: 'Atoms', subject: Subject.PHYSICS },
    { id: 'p27', name: 'Nuclei', subject: Subject.PHYSICS },
    { id: 'p28', name: 'Semiconductor Electronics', subject: Subject.PHYSICS },
  ],
  [Subject.CHEMISTRY]: [
    { id: 'c1', name: 'Some Basic Concepts of Chemistry', subject: Subject.CHEMISTRY },
    { id: 'c2', name: 'Structure of Atom', subject: Subject.CHEMISTRY },
    { id: 'c3', name: 'Classification of Elements & Periodicity', subject: Subject.CHEMISTRY },
    { id: 'c4', name: 'Chemical Bonding and Molecular Structure', subject: Subject.CHEMISTRY },
    { id: 'c5', name: 'Thermodynamics', subject: Subject.CHEMISTRY },
    { id: 'c6', name: 'Equilibrium', subject: Subject.CHEMISTRY },
    { id: 'c7', name: 'Redox Reactions', subject: Subject.CHEMISTRY },
    { id: 'c8', name: 'Solutions', subject: Subject.CHEMISTRY },
    { id: 'c9', name: 'Electrochemistry', subject: Subject.CHEMISTRY },
    { id: 'c10', name: 'Chemical Kinetics', subject: Subject.CHEMISTRY },
    { id: 'c11', name: 'Surface Chemistry', subject: Subject.CHEMISTRY },
    { id: 'c12', name: 'General Principles of Isolation of Elements', subject: Subject.CHEMISTRY },
    { id: 'c13', name: 'p-Block Elements', subject: Subject.CHEMISTRY },
    { id: 'c14', name: 'd and f Block Elements', subject: Subject.CHEMISTRY },
    { id: 'c15', name: 'Coordination Compounds', subject: Subject.CHEMISTRY },
    { id: 'c16', name: 'Haloalkanes and Haloarenes', subject: Subject.CHEMISTRY },
    { id: 'c17', name: 'Alcohols, Phenols and Ethers', subject: Subject.CHEMISTRY },
    { id: 'c18', name: 'Aldehydes, Ketones and Carboxylic Acids', subject: Subject.CHEMISTRY },
    { id: 'c19', name: 'Amines', subject: Subject.CHEMISTRY },
    { id: 'c20', name: 'Biomolecules', subject: Subject.CHEMISTRY },
    { id: 'c21', name: 'Polymers', subject: Subject.CHEMISTRY },
    { id: 'c22', name: 'Chemistry in Everyday Life', subject: Subject.CHEMISTRY },
  ],
  [Subject.MATHS]: [
    { id: 'm1', name: 'Sets, Relations and Functions', subject: Subject.MATHS },
    { id: 'm2', name: 'Trigonometric Functions', subject: Subject.MATHS },
    { id: 'm3', name: 'Complex Numbers and Quadratic Equations', subject: Subject.MATHS },
    { id: 'm4', name: 'Linear Inequalities', subject: Subject.MATHS },
    { id: 'm5', name: 'Permutations and Combinations', subject: Subject.MATHS },
    { id: 'm6', name: 'Binomial Theorem', subject: Subject.MATHS },
    { id: 'm7', name: 'Sequence and Series', subject: Subject.MATHS },
    { id: 'm8', name: 'Straight Lines', subject: Subject.MATHS },
    { id: 'm9', name: 'Conic Sections', subject: Subject.MATHS },
    { id: 'm10', name: 'Introduction to Three Dimensional Geometry', subject: Subject.MATHS },
    { id: 'm11', name: 'Limits and Derivatives', subject: Subject.MATHS },
    { id: 'm12', name: 'Mathematical Reasoning', subject: Subject.MATHS },
    { id: 'm13', name: 'Statistics', subject: Subject.MATHS },
    { id: 'm14', name: 'Probability', subject: Subject.MATHS },
    { id: 'm15', name: 'Inverse Trigonometric Functions', subject: Subject.MATHS },
    { id: 'm16', name: 'Matrices', subject: Subject.MATHS },
    { id: 'm17', name: 'Determinants', subject: Subject.MATHS },
    { id: 'm18', name: 'Continuity and Differentiability', subject: Subject.MATHS },
    { id: 'm19', name: 'Applications of Derivatives', subject: Subject.MATHS },
    { id: 'm20', name: 'Integrals', subject: Subject.MATHS },
    { id: 'm21', name: 'Application of Integrals', subject: Subject.MATHS },
    { id: 'm22', name: 'Differential Equations', subject: Subject.MATHS },
    { id: 'm23', name: 'Vector Algebra', subject: Subject.MATHS },
    { id: 'm24', name: 'Three Dimensional Geometry', subject: Subject.MATHS },
    { id: 'm25', name: 'Linear Programming', subject: Subject.MATHS },
  ],
  [Subject.BIOLOGY]: [
    { id: 'b1', name: 'The Living World', subject: Subject.BIOLOGY },
    { id: 'b2', name: 'Biological Classification', subject: Subject.BIOLOGY },
    { id: 'b3', name: 'Plant Kingdom', subject: Subject.BIOLOGY },
    { id: 'b4', name: 'Animal Kingdom', subject: Subject.BIOLOGY },
    { id: 'b5', name: 'Morphology of Flowering Plants', subject: Subject.BIOLOGY },
    { id: 'b6', name: 'Anatomy of Flowering Plants', subject: Subject.BIOLOGY },
    { id: 'b7', name: 'Structural Organisation in Animals', subject: Subject.BIOLOGY },
    { id: 'b8', name: 'Cell: The Unit of Life', subject: Subject.BIOLOGY },
    { id: 'b9', name: 'Biomolecules', subject: Subject.BIOLOGY },
    { id: 'b10', name: 'Cell Cycle and Cell Division', subject: Subject.BIOLOGY },
    { id: 'b11', name: 'Transport in Plants', subject: Subject.BIOLOGY },
    { id: 'b12', name: 'Mineral Nutrition', subject: Subject.BIOLOGY },
    { id: 'b13', name: 'Photosynthesis in Higher Plants', subject: Subject.BIOLOGY },
    { id: 'b14', name: 'Respiration in Plants', subject: Subject.BIOLOGY },
    { id: 'b15', name: 'Plant Growth and Development', subject: Subject.BIOLOGY },
    { id: 'b16', name: 'Digestion and Absorption', subject: Subject.BIOLOGY },
    { id: 'b17', name: 'Breathing and Exchange of Gases', subject: Subject.BIOLOGY },
    { id: 'b18', name: 'Body Fluids and Circulation', subject: Subject.BIOLOGY },
    { id: 'b19', name: 'Excretory Products and their Elimination', subject: Subject.BIOLOGY },
    { id: 'b20', name: 'Locomotion and Movement', subject: Subject.BIOLOGY },
    { id: 'b21', name: 'Neural Control and Coordination', subject: Subject.BIOLOGY },
    { id: 'b22', name: 'Chemical Coordination and Integration', subject: Subject.BIOLOGY },
    { id: 'b23', name: 'Reproduction in Organisms', subject: Subject.BIOLOGY },
    { id: 'b24', name: 'Sexual Reproduction in Flowering Plants', subject: Subject.BIOLOGY },
    { id: 'b25', name: 'Human Reproduction', subject: Subject.BIOLOGY },
    { id: 'b26', name: 'Reproductive Health', subject: Subject.BIOLOGY },
    { id: 'b27', name: 'Principles of Inheritance and Variation', subject: Subject.BIOLOGY },
    { id: 'b28', name: 'Molecular Basis of Inheritance', subject: Subject.BIOLOGY },
    { id: 'b29', name: 'Evolution', subject: Subject.BIOLOGY },
    { id: 'b30', name: 'Human Health and Disease', subject: Subject.BIOLOGY },
    { id: 'b31', name: 'Strategies for Enhancement in Food Production', subject: Subject.BIOLOGY },
    { id: 'b32', name: 'Microbes in Human Welfare', subject: Subject.BIOLOGY },
    { id: 'b33', name: 'Biotechnology: Principles and Processes', subject: Subject.BIOLOGY },
    { id: 'b34', name: 'Biotechnology and its Applications', subject: Subject.BIOLOGY },
    { id: 'b35', name: 'Organisms and Populations', subject: Subject.BIOLOGY },
    { id: 'b36', name: 'Ecosystem', subject: Subject.BIOLOGY },
    { id: 'b37', name: 'Biodiversity and Conservation', subject: Subject.BIOLOGY },
    { id: 'b38', name: 'Environmental Issues', subject: Subject.BIOLOGY },
  ]
};